### ISSUE TITLE
Remove the language switcher

### ISSUE THREAD

**Issue by Sebazzz** [Sebazzz/CR-6-touchscreen#1]
Related: Sebazzz/Marlin#2

Let's drop support for Chinese for now. 

[ ] Remove the language switcher
[ ] Remove the toggle button

**Comment by Sebazzz** [comment]
@Nushio Can you drop the language option from the 47_E_Control.bmp, then at my side I will remove the toggle switch. Just keep the space empty for now - I don't want to mess with moving up the Restore Factory and Info options just yet.

**Comment by Nushio** [comment]
Done. I also provided a pre-exported BMP on the images_source called 47_E_Control_tmp.bmp if you want to mess around moving Restore Factory and Info ;-)

**Comment by Sebazzz** [comment]
@Nushio Got it - removed the interface stuff in e96e15b. 

In b27458922 I added a note, apparently any changed BMPs must be placed in the DWIN_SOURCE folder. Otherwise they get overwritten.
